### ISSUE TITLE
Does not work well for JIRA-7.1

### ISSUE THREAD

**Issue by 4ndrej** [pearj/openam-crowdprovider#1]
Hello,
in JIRA 7.1 there was a change in gadgets, now a number of charts are generated using Javascript in the browser rather than server-side with Java.
This had significant performance improvements as the server was offloading processing to the browsers and resulted in less CPU usage. Part of the change modified the way JIRA previously operated, and now it is required that the server can connect to itself.

The result is that this crowd provider no longer works well with JIRA7.1+ because the gadgets are left untranslated.

More info about this issue is at https://confluence.atlassian.com/jirakb/how-to-fix-gadget-titles-showing-as-__msg_gadget-813697086.html

Could you please update this crowd provider to work well with JIRA-7.1 and later?

Thanks,
a.

**Comment by pearj** [comment]
Hi,

I no longer use this plugin and have no intention of updating it again.

Instead, we have opted to use a free SAML plugin that works fairly well with OpenAM, we use it internally and on a client site. I believe ForgeRock themselves use it too for [bugster](https://bugster.forgerock.org).

See:
* https://github.com/bitium/jira-saml-plugin
* https://marketplace.atlassian.com/plugins/com.bitium.jira.SAML2PluginJira/server/overview
